import "@/styles/globals.css"
import Head from "next/head"
import type { AppProps } from "next/app"
import styles from "@/styles/Home.module.css"
import Navbar from "@/components/Navbar/Navbar"

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Romas Bitinas. Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Component {...pageProps}>
        <main className={styles.main}>{pageProps.children}</main>
      </Component>
    </>
  )
}
