import Head from "next/head"
import { Inter } from "@next/font/google"
import styles from "@/styles/Home.module.css"
import Animated from "@/components/Animated"
const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Romas Bitinas. Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.hero}>
          <Animated l={1} className={styles.title} element="h1">
            Hello.
          </Animated>
          <Animated l={3} className={styles.title} element="h1">
            I am Romas. I am a full stack developer.
          </Animated>
          <Animated l={6} className={styles.title} element="h1">
            My main stack is React, Node.js, TypeScript
          </Animated>
          <Animated l={8} className={styles.title} element="h1">
            But I am eager to learn new things.
          </Animated>
        </section>
        <section className={styles.aboutMe}></section>
      </main>
    </>
  )
}
